#pragma once

#include "BloomLib/Bloom.h"
#include "BloomLib/NamespacedString.h"

namespace Sexy
{
class ResourceManager;
class Image;
class Font;
BLOOM_API Image *LoadImageById(ResourceManager *theManager, int theId);
BLOOM_API void ReplaceImageById(ResourceManager *theManager, int theId, Image *theImage);
BLOOM_API bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

BLOOM_API bool ExtractResourcesByName(ResourceManager *theManager, const char *theName);

// DelayLoad_Almanac Resources
BLOOM_API bool ExtractDelayLoad_AlmanacResources(ResourceManager *theMgr);

extern BLOOM_API Image *IMAGE_ALMANAC_INDEXBACK;
extern BLOOM_API Image *IMAGE_ALMANAC_PLANTBACK;
extern BLOOM_API Image *IMAGE_ALMANAC_ZOMBIEBACK;
extern BLOOM_API Image *IMAGE_ALMANAC_PLANTCARD;
extern BLOOM_API Image *IMAGE_ALMANAC_ZOMBIECARD;
extern BLOOM_API Image *IMAGE_ALMANAC_ZOMBIEWINDOW;
extern BLOOM_API Image *IMAGE_ALMANAC_ZOMBIEWINDOW2;
extern BLOOM_API Image *IMAGE_ALMANAC_ZOMBIEBLANK;
extern BLOOM_API Image *IMAGE_ALMANAC_GROUNDDAY;
extern BLOOM_API Image *IMAGE_ALMANAC_GROUNDNIGHT;
extern BLOOM_API Image *IMAGE_ALMANAC_GROUNDPOOL;
extern BLOOM_API Image *IMAGE_ALMANAC_GROUNDNIGHTPOOL;
extern BLOOM_API Image *IMAGE_ALMANAC_GROUNDROOF;
extern BLOOM_API Image *IMAGE_ALMANAC_GROUNDICE;
extern BLOOM_API Image *IMAGE_ALMANAC_CLOSEBUTTON;
extern BLOOM_API Image *IMAGE_ALMANAC_CLOSEBUTTONHIGHLIGHT;
extern BLOOM_API Image *IMAGE_ALMANAC_INDEXBUTTON;
extern BLOOM_API Image *IMAGE_ALMANAC_INDEXBUTTONHIGHLIGHT;

// DelayLoad_AwardScreen Resources
BLOOM_API bool ExtractDelayLoad_AwardScreenResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_AWARDSCREEN_BACK;

// DelayLoad_Background1 Resources
BLOOM_API bool ExtractDelayLoad_Background1Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND1;
extern BLOOM_API Image *IMAGE_BACKGROUND1_GAMEOVER_INTERIOR_OVERLAY;
extern BLOOM_API Image *IMAGE_BACKGROUND1_GAMEOVER_MASK;

// DelayLoad_Background2 Resources
BLOOM_API bool ExtractDelayLoad_Background2Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND2;
extern BLOOM_API Image *IMAGE_BACKGROUND2_GAMEOVER_INTERIOR_OVERLAY;
extern BLOOM_API Image *IMAGE_BACKGROUND2_GAMEOVER_MASK;

// DelayLoad_Background3 Resources
BLOOM_API bool ExtractDelayLoad_Background3Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND3;
extern BLOOM_API Image *IMAGE_BACKGROUND3_GAMEOVER_INTERIOR_OVERLAY;
extern BLOOM_API Image *IMAGE_BACKGROUND3_GAMEOVER_MASK;

// DelayLoad_Background4 Resources
BLOOM_API bool ExtractDelayLoad_Background4Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND4;
extern BLOOM_API Image *IMAGE_BACKGROUND4_GAMEOVER_INTERIOR_OVERLAY;
extern BLOOM_API Image *IMAGE_BACKGROUND4_GAMEOVER_MASK;
extern BLOOM_API Image *IMAGE_FOG;
extern BLOOM_API Image *IMAGE_FOG_SOFTWARE;

// DelayLoad_Background5 Resources
BLOOM_API bool ExtractDelayLoad_Background5Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND5;
extern BLOOM_API Image *IMAGE_BACKGROUND5_GAMEOVER_MASK;

// DelayLoad_Background6 Resources
BLOOM_API bool ExtractDelayLoad_Background6Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND6BOSS;
extern BLOOM_API Image *IMAGE_BACKGROUND6_GAMEOVER_MASK;

// DelayLoad_BackgroundUnsodded Resources
BLOOM_API bool ExtractDelayLoad_BackgroundUnsoddedResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND1UNSODDED;
extern BLOOM_API Image *IMAGE_SOD1ROW;
extern BLOOM_API Image *IMAGE_SOD3ROW;

// DelayLoad_ChallengeScreen Resources
BLOOM_API bool ExtractDelayLoad_ChallengeScreenResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_CHALLENGE_BACKGROUND;
extern BLOOM_API Image *IMAGE_CHALLENGE_WINDOW;
extern BLOOM_API Image *IMAGE_CHALLENGE_WINDOW_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_CHALLENGE_BLANK;
extern BLOOM_API Image *IMAGE_CHALLENGE_THUMBNAILS;
extern BLOOM_API Image *IMAGE_SURVIVAL_THUMBNAILS;
extern BLOOM_API Image *IMAGE_LOCK;
extern BLOOM_API Image *IMAGE_LOCK_OPEN;

// DelayLoad_Credits Resources
BLOOM_API bool ExtractDelayLoad_CreditsResources(ResourceManager *theMgr);
extern BLOOM_API Font *FONT_BRIANNETOD32;
extern BLOOM_API Font *FONT_BRIANNETOD32BLACK;
extern BLOOM_API Image *IMAGE_REANIM_SUNFLOWER_HEAD_SING1;
extern BLOOM_API Image *IMAGE_REANIM_SUNFLOWER_HEAD_SING2;
extern BLOOM_API Image *IMAGE_REANIM_SUNFLOWER_HEAD_SING3;
extern BLOOM_API Image *IMAGE_REANIM_SUNFLOWER_HEAD_SING4;
extern BLOOM_API Image *IMAGE_REANIM_SUNFLOWER_HEAD_SING5;
extern BLOOM_API Image *IMAGE_REANIM_SUNFLOWER_HEAD_WINK;
extern BLOOM_API Image *IMAGE_REANIM_CREDITS_DISCOLIGHTS;
extern BLOOM_API Image *IMAGE_REANIM_CREDITS_FOGMACHINE;
extern BLOOM_API Image *IMAGE_CREDITS_ZOMBIENOTE;
extern BLOOM_API Image *IMAGE_CREDITS_PLAYBUTTON;

// DelayLoad_GreenHouseGarden Resources
BLOOM_API bool ExtractDelayLoad_GreenHouseGardenResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND_GREENHOUSE;

// DelayLoad_GreenHouseOverlay Resources
BLOOM_API bool ExtractDelayLoad_GreenHouseOverlayResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND_GREENHOUSE_OVERLAY;

// DelayLoad_MushroomGarden Resources
BLOOM_API bool ExtractDelayLoad_MushroomGardenResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BACKGROUND_MUSHROOMGARDEN;

// DelayLoad_Store Resources
BLOOM_API bool ExtractDelayLoad_StoreResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_STORE_BACKGROUND;
extern BLOOM_API Image *IMAGE_STORE_BACKGROUNDNIGHT;
extern BLOOM_API Image *IMAGE_STORE_CAR;
extern BLOOM_API Image *IMAGE_STORE_CAR_NIGHT;
extern BLOOM_API Image *IMAGE_STORE_CARCLOSED;
extern BLOOM_API Image *IMAGE_STORE_CARCLOSED_NIGHT;
extern BLOOM_API Image *IMAGE_STORE_HATCHBACKOPEN;
extern BLOOM_API Image *IMAGE_STORE_SIGN;
extern BLOOM_API Image *IMAGE_STORE_MAINMENUBUTTON;
extern BLOOM_API Image *IMAGE_STORE_MAINMENUBUTTONDOWN;
extern BLOOM_API Image *IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT;
extern BLOOM_API Image *IMAGE_STORE_NEXTBUTTON;
extern BLOOM_API Image *IMAGE_STORE_NEXTBUTTONHIGHLIGHT;
extern BLOOM_API Image *IMAGE_STORE_NEXTBUTTONDISABLED;
extern BLOOM_API Image *IMAGE_STORE_PREVBUTTON;
extern BLOOM_API Image *IMAGE_STORE_PREVBUTTONHIGHLIGHT;
extern BLOOM_API Image *IMAGE_STORE_PREVBUTTONDISABLED;
extern BLOOM_API Image *IMAGE_STORE_PRICETAG;
extern BLOOM_API Image *IMAGE_STORE_PACKETUPGRADE;
extern BLOOM_API Image *IMAGE_STORE_MUSHROOMGARDENICON;
extern BLOOM_API Image *IMAGE_STORE_AQUARIUMGARDENICON;
extern BLOOM_API Image *IMAGE_STORE_TREEOFWISDOMICON;
extern BLOOM_API Image *IMAGE_STORE_FIRSTAIDWALLNUTICON;
extern BLOOM_API Image *IMAGE_STORE_PVZICON;

// DelayLoad_TreeOfWisdom Resources
BLOOM_API bool ExtractDelayLoad_TreeOfWisdomResources(ResourceManager *theMgr);

// DelayLoad_Zombatar Resources
BLOOM_API bool ExtractDelayLoad_ZombatarResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_BG;
extern BLOOM_API Image *IMAGE_ZOMBATAR_PREV_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_PREV_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_NEXT_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_NEXT_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ZOMBIE_BLANK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ZOMBIE_BLANK_SKIN;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKGROUND_CRAZYDAVE;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKGROUND_MENU;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKGROUND_MENU_DOS;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKGROUND_ROOF;
extern BLOOM_API Image *IMAGE_ZOMBATAR_WIDGET_BG;
extern BLOOM_API Image *IMAGE_ZOMBATAR_WIDGET_INNER_BG;
extern BLOOM_API Image *IMAGE_ZOMBATAR_COLORS_BG;
extern BLOOM_API Image *IMAGE_ZOMBATAR_LOGO;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKDROPS_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKDROPS_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKDROPS_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_SKIN_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_SKIN_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_BUTTON_OVER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_BG_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TRIPTYCH;
extern BLOOM_API Image *IMAGE_ZOMBATAR_COLORPICKER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_COLORPICKER_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_COLORPICKER_NONE;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_BG_NONE;
extern BLOOM_API Image *IMAGE_ZOMBATAR_COLORS_BG_SMALL;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_1;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_2;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_3;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_4;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_5;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_6;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_7;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_8;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_9;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_10;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_11;
extern BLOOM_API Image *IMAGE_ZOMBATAR_CLOTHES_12;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_1;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_2;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_3;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_4;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_5;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_6;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_7;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_8;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_9;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_10;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_11;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_12;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_13;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_14;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_1;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_2;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_3;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_4;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_5;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_6;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_7;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_8;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_9;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_10;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_11;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_12;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_13;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_14;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_15;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_16;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_1;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_2;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_3;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_4;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_5;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_6;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_7;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_8;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_9;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_10;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_11;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_12;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_13;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_14;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_15;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_16;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_1;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_2;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_3;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_4;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_5;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_6;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_7;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_8;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_9;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_10;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_11;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_12;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_13;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_14;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_15;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_16;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_17;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_18;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_19;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_20;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_21;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_22;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_23;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_24;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_1;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_2;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_3;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_4;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_5;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_6;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_7;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_8;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_9;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_10;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_11;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_12;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_13;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TIDBITS_14;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_1;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_2;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_3;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_4;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_5;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_6;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_7;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_8;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_9;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_10;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_11;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_12;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_13;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_14;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_1_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_1_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_2_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_11_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_12_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_13_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_14_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HAIR_15_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_1_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_4_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_8_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_9_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_10_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_11_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_12_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_14_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_15_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_16_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_18_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_21_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_22_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_23_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FACIALHAIR_24_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_1_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_2_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_3_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_4_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_5_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_6_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_7_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_8_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_9_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_10_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_11_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_EYEWEAR_12_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_3_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_6_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_7_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_8_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_9_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_HATS_11_MASK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACKGROUND_BLANK;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_15;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCESSORY_16;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCEPT_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_ACCEPT_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FINISHED_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_FINISHED_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_MAIN_BG;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACK_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BACK_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TOS_ARROW;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BEGIN_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_BEGIN_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TOS_SLIDER;
extern BLOOM_API Image *IMAGE_ZOMBATAR_TOS_SLIDER_THUMB;
extern BLOOM_API Image *IMAGE_ZOMBATAR_DISPLAY_WINDOW;
extern BLOOM_API Image *IMAGE_ZOMBATAR_MAINMENUBACK_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ZOMBATAR_VIEW_BUTTON;
extern BLOOM_API Image *IMAGE_ZOMBATAR_VIEW_BUTTON_HIGHLIGHT;

// DelayLoad_ZombieFinalNote Resources
BLOOM_API bool ExtractDelayLoad_ZombieFinalNoteResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBIE_FINAL_NOTE;

// DelayLoad_ZombieNote Resources
BLOOM_API bool ExtractDelayLoad_ZombieNoteResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBIE_NOTE;

// DelayLoad_ZombieNote1 Resources
BLOOM_API bool ExtractDelayLoad_ZombieNote1Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBIE_NOTE1;

// DelayLoad_ZombieNote2 Resources
BLOOM_API bool ExtractDelayLoad_ZombieNote2Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBIE_NOTE2;

// DelayLoad_ZombieNote3 Resources
BLOOM_API bool ExtractDelayLoad_ZombieNote3Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBIE_NOTE3;

// DelayLoad_ZombieNote4 Resources
BLOOM_API bool ExtractDelayLoad_ZombieNote4Resources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBIE_NOTE4;

// DelayLoad_ZombieNoteHelp Resources
BLOOM_API bool ExtractDelayLoad_ZombieNoteHelpResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_ZOMBIE_NOTE_HELP;

// DelayLoad_Zombiquarium Resources
BLOOM_API bool ExtractDelayLoad_ZombiquariumResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_AQUARIUM1;
extern BLOOM_API Image *IMAGE_WAVECENTER;
extern BLOOM_API Image *IMAGE_WAVESIDE;

// Init Resources
bool ExtractInitResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_BLANK;
extern BLOOM_API Image *IMAGE_POPCAP_LOGO;
extern BLOOM_API Image *IMAGE_PARTNER_LOGO;

// LoaderBar Resources
BLOOM_API bool ExtractLoaderBarResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_TITLESCREEN;
extern BLOOM_API Image *IMAGE_LOADBAR_DIRT;
extern BLOOM_API Image *IMAGE_LOADBAR_GRASS;
extern BLOOM_API Image *IMAGE_PVZ_LOGO;
extern BLOOM_API Image *IMAGE_REANIM_SODROLLCAP;
extern BLOOM_API Font *FONT_BRIANNETOD16;
extern BLOOM_API int SOUND_BUTTONCLICK;
extern BLOOM_API int SOUND_LOADINGBAR_FLOWER;
extern BLOOM_API int SOUND_LOADINGBAR_ZOMBIE;

// LoadingFonts Resources
BLOOM_API bool ExtractLoadingFontsResources(ResourceManager *theMgr);
extern BLOOM_API Image *FONT_IMAGE_HOUSEOFTERROR28;
extern BLOOM_API Font *FONT_HOUSEOFTERROR28;
extern BLOOM_API Font *FONT_HOUSEOFTERROR20;
extern BLOOM_API Font *FONT_HOUSEOFTERROR16;
extern BLOOM_API Font *FONT_TINYBOLD;
extern BLOOM_API Font *FONT_CONTINUUMBOLD14;
extern BLOOM_API Font *FONT_CONTINUUMBOLD14OUTLINE;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT12;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT15;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT18;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT18BRIGHTGREENINSET;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT18GREENINSET;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT18YELLOW;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT24;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT36BRIGHTGREENINSET;
extern BLOOM_API Font *FONT_DWARVENTODCRAFT36GREENINSET;
extern BLOOM_API Font *FONT_PICO129;
extern BLOOM_API Font *FONT_BRIANNETOD12;

// LoadingImages Resources
BLOOM_API bool ExtractLoadingImagesResources(ResourceManager *theMgr);
extern BLOOM_API Image *IMAGE_EDITBOX;
extern BLOOM_API Image *IMAGE_DIALOG_TOPLEFT;
extern BLOOM_API Image *IMAGE_DIALOG_TOPMIDDLE;
extern BLOOM_API Image *IMAGE_DIALOG_TOPRIGHT;
extern BLOOM_API Image *IMAGE_DIALOG_CENTERLEFT;
extern BLOOM_API Image *IMAGE_DIALOG_CENTERMIDDLE;
extern BLOOM_API Image *IMAGE_DIALOG_CENTERRIGHT;
extern BLOOM_API Image *IMAGE_DIALOG_BOTTOMLEFT;
extern BLOOM_API Image *IMAGE_DIALOG_BOTTOMMIDDLE;
extern BLOOM_API Image *IMAGE_DIALOG_BOTTOMRIGHT;
extern BLOOM_API Image *IMAGE_DIALOG_BIGBOTTOMLEFT;
extern BLOOM_API Image *IMAGE_DIALOG_BIGBOTTOMMIDDLE;
extern BLOOM_API Image *IMAGE_DIALOG_BIGBOTTOMRIGHT;
extern BLOOM_API Image *IMAGE_DIALOG_HEADER;
extern BLOOM_API Image *IMAGE_BUTTON_LEFT;
extern BLOOM_API Image *IMAGE_BUTTON_MIDDLE;
extern BLOOM_API Image *IMAGE_BUTTON_RIGHT;
extern BLOOM_API Image *IMAGE_BUTTON_DOWN_LEFT;
extern BLOOM_API Image *IMAGE_BUTTON_DOWN_MIDDLE;
extern BLOOM_API Image *IMAGE_BUTTON_DOWN_RIGHT;
extern BLOOM_API Image *IMAGE_SEEDCHOOSER_BACKGROUND;
extern BLOOM_API Image *IMAGE_SEEDCHOOSER_BUTTON;
extern BLOOM_API Image *IMAGE_SEEDCHOOSER_BUTTON_DISABLED;
extern BLOOM_API Image *IMAGE_SEEDCHOOSER_BUTTON_GLOW;
extern BLOOM_API Image *IMAGE_SEEDCHOOSER_BUTTON2;
extern BLOOM_API Image *IMAGE_SEEDCHOOSER_BUTTON2_GLOW;
extern BLOOM_API Image *IMAGE_SEEDCHOOSER_IMITATERADDON;
extern BLOOM_API Image *IMAGE_SEEDS;
extern BLOOM_API Image *IMAGE_SEEDPACKET_LARGER;
extern BLOOM_API Image *IMAGE_SEEDPACKETSILHOUETTE;
extern BLOOM_API Image *IMAGE_FLAGMETER;
extern BLOOM_API Image *IMAGE_FLAGMETERLEVELPROGRESS;
extern BLOOM_API Image *IMAGE_FLAGMETERPARTS;
extern BLOOM_API Image *IMAGE_TROPHY;
extern BLOOM_API Image *IMAGE_TROPHY_HI_RES;
extern BLOOM_API Image *IMAGE_MINIGAME_TROPHY;
extern BLOOM_API Image *IMAGE_ZOMBIE_NOTE_SMALL;
extern BLOOM_API Image *IMAGE_TACO;
extern BLOOM_API Image *IMAGE_CARKEYS;
extern BLOOM_API Image *IMAGE_ALMANAC;
extern BLOOM_API Image *IMAGE_ICON_POOLCLEANER;
extern BLOOM_API Image *IMAGE_ICON_ROOFCLEANER;
extern BLOOM_API Image *IMAGE_ICON_RAKE;
extern BLOOM_API Image *IMAGE_BRAIN;
extern BLOOM_API Image *IMAGE_MONEYBAG;
extern BLOOM_API Image *IMAGE_MONEYBAG_HI_RES;
extern BLOOM_API Image *IMAGE_CHOCOLATE;
extern BLOOM_API Image *IMAGE_OPTIONS_BACKTOGAMEBUTTON0;
extern BLOOM_API Image *IMAGE_OPTIONS_BACKTOGAMEBUTTON2;
extern BLOOM_API Image *IMAGE_OPTIONS_CHECKBOX0;
extern BLOOM_API Image *IMAGE_OPTIONS_CHECKBOX1;
extern BLOOM_API Image *IMAGE_OPTIONS_MENUBACK;
extern BLOOM_API Image *IMAGE_OPTIONS_SLIDERKNOB2;
extern BLOOM_API Image *IMAGE_OPTIONS_SLIDERSLOT;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_HELP1;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_HELP2;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_OPTIONS1;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_OPTIONS2;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_QUIT1;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_QUIT2;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_ALMANAC;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_ALMANACHIGHLIGHT;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_STORE;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_STOREHIGHLIGHT;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_LEVELNUMBERS;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_ZENGARDEN;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_ZENGARDENHIGHLIGHT;
extern BLOOM_API Image *IMAGE_STORE_SPEECHBUBBLE;
extern BLOOM_API Image *IMAGE_STORE_SPEECHBUBBLE2;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_MOREWAYSTOPLAY_BG;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_ACHIEVEMENTS_PEDESTAL;
extern BLOOM_API Image *IMAGE_SELECTORSCREEN_ACHIEVEMENTS_PEDESTAL_PRESS;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_BEJEWELED;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_BOOKWORM;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_CHINA;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_CHUZZLE;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_HOLE_TILE;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_PEGGLE;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_PIPE;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_ZUMA;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_ICONS;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_BACK_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_QUICKPLAY_MINIGAMES_BUTTON;
extern BLOOM_API Image *IMAGE_QUICKPLAY_MINIGAMES_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_QUICKPLAY_MINIGAMES_CLOUD;
extern BLOOM_API Image *IMAGE_QUICKPLAY_PUZZLES_BUTTON;
extern BLOOM_API Image *IMAGE_QUICKPLAY_PUZZLES_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_QUICKPLAY_PUZZLES_CLOUD;
extern BLOOM_API Image *IMAGE_QUICKPLAY_SURVIVAL_BUTTON;
extern BLOOM_API Image *IMAGE_QUICKPLAY_SURVIVAL_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_QUICKPLAY_SURVIVAL_CLOUD;
extern BLOOM_API Image *IMAGE_QUICKPLAY_BACK_BUTTON;
extern BLOOM_API Image *IMAGE_QUICKPLAY_BACK_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_MORE_ROCK;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_MORE_BUTTON;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_MORE_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_TOP_BUTTON;
extern BLOOM_API Image *IMAGE_ACHEESEMENTS_TOP_BUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_SHOVEL;
extern BLOOM_API Image *IMAGE_SHOVEL_HI_RES;
extern BLOOM_API Image *IMAGE_TOMBSTONES;
extern BLOOM_API Image *IMAGE_TOMBSTONE_MOUNDS;
extern BLOOM_API Image *IMAGE_NIGHT_GRAVE_GRAPHIC;
extern BLOOM_API Image *IMAGE_CRATER;
extern BLOOM_API Image *IMAGE_CRATER_FADING;
extern BLOOM_API Image *IMAGE_CRATER_ROOF_CENTER;
extern BLOOM_API Image *IMAGE_CRATER_ROOF_LEFT;
extern BLOOM_API Image *IMAGE_CRATER_WATER_DAY;
extern BLOOM_API Image *IMAGE_CRATER_WATER_NIGHT;
extern BLOOM_API Image *IMAGE_COBCANNON_TARGET;
extern BLOOM_API Image *IMAGE_COBCANNON_POPCORN;
extern BLOOM_API Image *IMAGE_FERTILIZER;
extern BLOOM_API Image *IMAGE_WATERINGCAN;
extern BLOOM_API Image *IMAGE_WATERINGCANGOLD;
extern BLOOM_API Image *IMAGE_PHONOGRAPH;
extern BLOOM_API Image *IMAGE_BEGHOULED_TWIST_OVERLAY;
extern BLOOM_API Image *IMAGE_ZEN_GOLDTOOLRETICLE;
extern BLOOM_API Image *IMAGE_ZEN_GARDENGLOVE;
extern BLOOM_API Image *IMAGE_ZEN_MONEYSIGN;
extern BLOOM_API Image *IMAGE_ZEN_NEXTGARDEN;
extern BLOOM_API Image *IMAGE_ZEN_WHEELBARROW;
extern BLOOM_API Image *IMAGE_ZENSHOPBUTTON;
extern BLOOM_API Image *IMAGE_ZENSHOPBUTTON_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_PRESENT;
extern BLOOM_API Image *IMAGE_PRESENTOPEN;
extern BLOOM_API Image *IMAGE_SUNFLOWER_TROPHY;
extern BLOOM_API Image *IMAGE_SLOTMACHINE_OVERLAY;
extern BLOOM_API Image *IMAGE_SCARY_POT;
extern BLOOM_API Image *IMAGE_BUG_SPRAY;
extern BLOOM_API Image *IMAGE_PLANTSPEECHBUBBLE;
extern BLOOM_API Image *IMAGE_WATERDROP;
extern BLOOM_API Image *IMAGE_TREEFOOD;
extern BLOOM_API Image *IMAGE_PACKET_PLANTS;
extern BLOOM_API Image *IMAGE_ZEN_NEED_ICONS;
extern BLOOM_API Image *IMAGE_PROJECTILEPEA;
extern BLOOM_API Image *IMAGE_PROJECTILESNOWPEA;
extern BLOOM_API Image *IMAGE_PROJECTILECACTUS;
extern BLOOM_API Image *IMAGE_DIRTSMALL;
extern BLOOM_API Image *IMAGE_DIRTBIG;
extern BLOOM_API Image *IMAGE_ROCKSMALL;
extern BLOOM_API Image *IMAGE_WATERPARTICLE;
extern BLOOM_API Image *IMAGE_WHITEWATER;
extern BLOOM_API Image *IMAGE_WHITEWATER_SHADOW;
extern BLOOM_API Image *IMAGE_MELONPULT_PARTICLES;
extern BLOOM_API Image *IMAGE_WINTERMELON_PARTICLES;
extern BLOOM_API Image *IMAGE_PROJECTILE_STAR;
extern BLOOM_API Image *IMAGE_SEEDBANK;
extern BLOOM_API Image *IMAGE_CONVEYORBELT_BACKDROP;
extern BLOOM_API Image *IMAGE_CONVEYORBELT;
extern BLOOM_API Image *IMAGE_SHOVELBANK;
extern BLOOM_API Image *IMAGE_SUNBANK;
extern BLOOM_API Image *IMAGE_COINBANK;
extern BLOOM_API Image *IMAGE_POOL;
extern BLOOM_API Image *IMAGE_POOL_NIGHT;
extern BLOOM_API Image *IMAGE_POOL_BASE;
extern BLOOM_API Image *IMAGE_POOL_BASE_NIGHT;
extern BLOOM_API Image *IMAGE_POOL_SHADING;
extern BLOOM_API Image *IMAGE_POOL_SHADING_NIGHT;
extern BLOOM_API Image *IMAGE_POOL_CAUSTIC_EFFECT;
extern BLOOM_API Image *IMAGE_PLANTSHADOW;
extern BLOOM_API Image *IMAGE_PLANTSHADOW2;
extern BLOOM_API Image *IMAGE_PEA_SHADOWS;
extern BLOOM_API Image *IMAGE_WALLNUT_BOWLINGSTRIPE;
extern BLOOM_API Image *IMAGE_ICE;
extern BLOOM_API Image *IMAGE_ICE_CAP;
extern BLOOM_API Image *IMAGE_ICE_SPARKLES;
extern BLOOM_API Image *IMAGE_IMITATERSEED;
extern BLOOM_API Image *IMAGE_ALMANAC_IMITATER;
extern BLOOM_API Image *IMAGE_IMITATERSEEDDISABLED;
extern BLOOM_API Image *IMAGE_ICETRAP;
extern BLOOM_API Image *IMAGE_ICETRAP2;
extern BLOOM_API Image *IMAGE_ICETRAP_PARTICLES;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOBSLED1;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOBSLED2;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOBSLED3;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOBSLED4;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOBSLED_INSIDE;
extern BLOOM_API Image *IMAGE_BUNGEECORD;
extern BLOOM_API Image *IMAGE_BUNGEETARGET;
extern BLOOM_API Image *IMAGE_SPOTLIGHT;
extern BLOOM_API Image *IMAGE_SPOTLIGHT2;
extern BLOOM_API Image *IMAGE_WHITEPIXEL;
extern BLOOM_API Image *IMAGE_ZOMBIEPOLEVAULTERHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEFOOTBALLHEAD;
extern BLOOM_API Image *IMAGE_POOLSPARKLY;
extern BLOOM_API Image *IMAGE_WALLNUTPARTICLESSMALL;
extern BLOOM_API Image *IMAGE_WALLNUTPARTICLESLARGE;
extern BLOOM_API Image *IMAGE_PEA_SPLATS;
extern BLOOM_API Image *IMAGE_STAR_PARTICLES;
extern BLOOM_API Image *IMAGE_STAR_SPLATS;
extern BLOOM_API Image *IMAGE_PEA_PARTICLES;
extern BLOOM_API Image *IMAGE_SNOWPEA_SPLATS;
extern BLOOM_API Image *IMAGE_SNOWPEA_PARTICLES;
extern BLOOM_API Image *IMAGE_SNOWPEA_PUFF;
extern BLOOM_API Image *IMAGE_SNOWFLAKES;
extern BLOOM_API Image *IMAGE_POTATOMINE_PARTICLES;
extern BLOOM_API Image *IMAGE_PUFFSHROOM_PUFF1;
extern BLOOM_API Image *IMAGE_ZAMBONISMOKE;
extern BLOOM_API Image *IMAGE_ZOMBIEDANCERHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEBALLOONHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEIMPHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEDIGGERHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEDIGGERARM;
extern BLOOM_API Image *IMAGE_ZOMBIEDOLPHINRIDERHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEPOGO;
extern BLOOM_API Image *IMAGE_ZOMBIEBACKUPDANCERHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEBOBSLEDHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIELADDERHEAD;
extern BLOOM_API Image *IMAGE_ZOMBIEYETIHEAD;
extern BLOOM_API Image *IMAGE_SEEDPACKETFLASH;
extern BLOOM_API Image *IMAGE_ZOMBIEJACKBOXARM;
extern BLOOM_API Image *IMAGE_IMITATERCLOUDS;
extern BLOOM_API Image *IMAGE_IMITATERPUFFS;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOSS_FIREBALL_PARTICLES;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOSS_ICEBALL_PARTICLES;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOSS_FIREBALL_GROUNDPARTICLES;
extern BLOOM_API Image *IMAGE_ZOMBIE_BOSS_ICEBALL_GROUNDPARTICLES;
extern BLOOM_API Image *IMAGE_DOOMSHROOM_EXPLOSION_BASE;
extern BLOOM_API Image *IMAGE_RAIN;
extern BLOOM_API Image *IMAGE_VASE_CHUNKS;
extern BLOOM_API Image *IMAGE_ZOMBOSS_PARTICLES;
extern BLOOM_API Image *IMAGE_AWARDPICKUPGLOW;
extern BLOOM_API Image *IMAGE_ZOMBIE_SEAWEED;
extern BLOOM_API Image *IMAGE_PINATA;
extern BLOOM_API Image *IMAGE_ZOMBIEFUTUREGLASSES;
extern BLOOM_API Image *IMAGE_DUST_PUFFS;
extern BLOOM_API Image *IMAGE_REANIM_WALLNUT_BODY;
extern BLOOM_API Image *IMAGE_REANIM_WALLNUT_CRACKED1;
extern BLOOM_API Image *IMAGE_REANIM_WALLNUT_CRACKED2;
extern BLOOM_API Image *IMAGE_REANIM_TALLNUT_CRACKED1;
extern BLOOM_API Image *IMAGE_REANIM_TALLNUT_CRACKED2;
extern BLOOM_API Image *IMAGE_REANIM_PUMPKIN_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_PUMPKIN_DAMAGE3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CONE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CONE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CONE3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BUCKET1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BUCKET2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BUCKET3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_SCREENDOOR1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_SCREENDOOR2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_SCREENDOOR3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_FLAG1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_FLAG3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_HAND;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_LOWER;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_PAPER_PAPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_PAPER_PAPER3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_PAPER_MADHEAD;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_ZAMBONI_WHEEL_FLAT;
extern BLOOM_API Image *IMAGE_REANIM_COIN_SILVER_DOLLAR;
extern BLOOM_API Image *IMAGE_REANIM_COIN_GOLD_DOLLAR;
extern BLOOM_API Image *IMAGE_REANIM_DIAMOND;
extern BLOOM_API Image *IMAGE_REANIM_COINGLOW;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_HAND;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BACKUP_INNERARM_HAND;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BACKUP_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_POLEVAULTER_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_OUTERARM_HAND;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BALLOON_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_IMP_ARM1_BONE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_IMP_ARM2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_DUCKXING;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_ZOMBIE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_FOOT2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_OUTERARM_LOWER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2_REDEYE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD_REDEYE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DIGGER_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DOLPHINRIDER_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_POGO_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_POGO_STICKHANDS2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_HAND;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_JACKBOX_BOX;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_JACKBOX_OUTERARM_LOWER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_SNORKLE_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BUNGI_HEAD_SCARED;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CATAPULT_BASKETBALL;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CATAPULT_POLE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_WITHBALL;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE_WITHBALL;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_CATAPULT_SIDING_DAMAGE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_LADDER_1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_LADDER_5;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_LADDER_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_ICEBALL;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_EYEGLOW_BLUE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_BOSS_MOUTHGLOW_BLUE;
extern BLOOM_API Image *IMAGE_REANIM_CABBAGEPULT_CABBAGE;
extern BLOOM_API Image *IMAGE_REANIM_CORNPULT_KERNAL;
extern BLOOM_API Image *IMAGE_REANIM_CORNPULT_BUTTER;
extern BLOOM_API Image *IMAGE_REANIM_CORNPULT_BUTTER_SPLAT;
extern BLOOM_API Image *IMAGE_REANIM_MELONPULT_MELON;
extern BLOOM_API Image *IMAGE_REANIM_WINTERMELON_PROJECTILE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_DIGGER_PICKAXE;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_HEAD_GROSSOUT;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES1;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES3;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES4;
extern BLOOM_API Image *IMAGE_REANIM_GARLIC_BODY2;
extern BLOOM_API Image *IMAGE_REANIM_GARLIC_BODY3;
extern BLOOM_API Image *IMAGE_REANIM_COBCANNON_COB;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_UPPER2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_HAND;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_SNORKLE_HEAD;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_ADVENTURE_BUTTON;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_ADVENTURE_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_STARTADVENTURE_BUTTON;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_STARTADVENTURE_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_SURVIVAL_BUTTON;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_SURVIVAL_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_CHALLENGES_BUTTON;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_CHALLENGES_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_VASEBREAKER_BUTTON;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_VASEBREAKER_HIGHLIGHT;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_WOODSIGN2_PRESS;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_WOODSIGN3_PRESS;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_BG;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_ALMANAC_SHADOW;
extern BLOOM_API Image *IMAGE_REANIM_SELECTORSCREEN_KEY_SHADOW;
extern BLOOM_API Image *IMAGE_REANIM_TREE_BG;
extern BLOOM_API Image *IMAGE_REANIM_POT_TOP_DARK;
extern BLOOM_API Image *IMAGE_REANIM_ZENGARDEN_BUGSPRAY_BOTTLE;
extern BLOOM_API Image *IMAGE_REANIM_STINKY_TURN3;
extern BLOOM_API Image *IMAGE_REANIM_CRAZYDAVE_MOUTH1;
extern BLOOM_API Image *IMAGE_REANIM_CRAZYDAVE_MOUTH4;
extern BLOOM_API Image *IMAGE_REANIM_CRAZYDAVE_MOUTH5;
extern BLOOM_API Image *IMAGE_REANIM_CRAZYDAVE_MOUTH6;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_MUSTACHE2;
extern BLOOM_API Image *IMAGE_REANIM_ZOMBIE_MUSTACHE3;

// LoadingSounds Resources
BLOOM_API bool ExtractLoadingSoundsResources(ResourceManager *theMgr);
extern BLOOM_API int SOUND_ACHIEVEMENT;
extern BLOOM_API int SOUND_AWOOGA;
extern BLOOM_API int SOUND_BLEEP;
extern BLOOM_API int SOUND_BUZZER;
extern BLOOM_API int SOUND_CHOMP;
extern BLOOM_API int SOUND_CHOMP2;
extern BLOOM_API int SOUND_CHOMPSOFT;
extern BLOOM_API int SOUND_EVILLAUGH;
extern BLOOM_API int SOUND_FLOOP;
extern BLOOM_API int SOUND_FROZEN;
extern BLOOM_API int SOUND_GULP;
extern BLOOM_API int SOUND_GROAN;
extern BLOOM_API int SOUND_GROAN2;
extern BLOOM_API int SOUND_GROAN3;
extern BLOOM_API int SOUND_GROAN4;
extern BLOOM_API int SOUND_GROAN5;
extern BLOOM_API int SOUND_GROAN6;
extern BLOOM_API int SOUND_LOSEMUSIC;
extern BLOOM_API int SOUND_MINDCONTROLLED;
extern BLOOM_API int SOUND_PAUSE;
extern BLOOM_API int SOUND_PLANT;
extern BLOOM_API int SOUND_PLANT2;
extern BLOOM_API int SOUND_POINTS;
extern BLOOM_API int SOUND_SEEDLIFT;
extern BLOOM_API int SOUND_SIREN;
extern BLOOM_API int SOUND_SLURP;
extern BLOOM_API int SOUND_SPLAT;
extern BLOOM_API int SOUND_SPLAT2;
extern BLOOM_API int SOUND_SPLAT3;
extern BLOOM_API int SOUND_SUKHBIR;
extern BLOOM_API int SOUND_SUKHBIR2;
extern BLOOM_API int SOUND_SUKHBIR3;
extern BLOOM_API int SOUND_SUKHBIR4;
extern BLOOM_API int SOUND_SUKHBIR5;
extern BLOOM_API int SOUND_SUKHBIR6;
extern BLOOM_API int SOUND_TAP;
extern BLOOM_API int SOUND_TAP2;
extern BLOOM_API int SOUND_THROW;
extern BLOOM_API int SOUND_THROW2;
extern BLOOM_API int SOUND_BLOVER;
extern BLOOM_API int SOUND_WINMUSIC;
extern BLOOM_API int SOUND_LAWNMOWER;
extern BLOOM_API int SOUND_BOING;
extern BLOOM_API int SOUND_JACKINTHEBOX;
extern BLOOM_API int SOUND_DIAMOND;
extern BLOOM_API int SOUND_DOLPHIN_APPEARS;
extern BLOOM_API int SOUND_DOLPHIN_BEFORE_JUMPING;
extern BLOOM_API int SOUND_POTATO_MINE;
extern BLOOM_API int SOUND_ZAMBONI;
extern BLOOM_API int SOUND_BALLOON_POP;
extern BLOOM_API int SOUND_THUNDER;
extern BLOOM_API int SOUND_ZOMBIESPLASH;
extern BLOOM_API int SOUND_BOWLING;
extern BLOOM_API int SOUND_BOWLINGIMPACT;
extern BLOOM_API int SOUND_BOWLINGIMPACT2;
extern BLOOM_API int SOUND_GRAVEBUSTERCHOMP;
extern BLOOM_API int SOUND_GRAVEBUTTON;
extern BLOOM_API int SOUND_LIMBS_POP;
extern BLOOM_API int SOUND_PLANTERN;
extern BLOOM_API int SOUND_POGO_ZOMBIE;
extern BLOOM_API int SOUND_SNOW_PEA_SPARKLES;
extern BLOOM_API int SOUND_PLANT_WATER;
extern BLOOM_API int SOUND_ZOMBIE_ENTERING_WATER;
extern BLOOM_API int SOUND_ZOMBIE_FALLING_1;
extern BLOOM_API int SOUND_ZOMBIE_FALLING_2;
extern BLOOM_API int SOUND_PUFF;
extern BLOOM_API int SOUND_FUME;
extern BLOOM_API int SOUND_HUGE_WAVE;
extern BLOOM_API int SOUND_SLOT_MACHINE;
extern BLOOM_API int SOUND_COIN;
extern BLOOM_API int SOUND_ROLL_IN;
extern BLOOM_API int SOUND_DIGGER_ZOMBIE;
extern BLOOM_API int SOUND_HATCHBACK_CLOSE;
extern BLOOM_API int SOUND_HATCHBACK_OPEN;
extern BLOOM_API int SOUND_KERNELPULT;
extern BLOOM_API int SOUND_KERNELPULT2;
extern BLOOM_API int SOUND_ZOMBAQUARIUM_DIE;
extern BLOOM_API int SOUND_BUNGEE_SCREAM;
extern BLOOM_API int SOUND_BUNGEE_SCREAM2;
extern BLOOM_API int SOUND_BUNGEE_SCREAM3;
extern BLOOM_API int SOUND_BUTTER;
extern BLOOM_API int SOUND_JACK_SURPRISE;
extern BLOOM_API int SOUND_JACK_SURPRISE2;
extern BLOOM_API int SOUND_NEWSPAPER_RARRGH;
extern BLOOM_API int SOUND_NEWSPAPER_RARRGH2;
extern BLOOM_API int SOUND_NEWSPAPER_RIP;
extern BLOOM_API int SOUND_SQUASH_HMM;
extern BLOOM_API int SOUND_SQUASH_HMM2;
extern BLOOM_API int SOUND_VASE_BREAKING;
extern BLOOM_API int SOUND_POOL_CLEANER;
extern BLOOM_API int SOUND_MAGNETSHROOM;
extern BLOOM_API int SOUND_LADDER_ZOMBIE;
extern BLOOM_API int SOUND_GARGANTUAR_THUMP;
extern BLOOM_API int SOUND_BASKETBALL;
extern BLOOM_API int SOUND_FIREPEA;
extern BLOOM_API int SOUND_IGNITE;
extern BLOOM_API int SOUND_IGNITE2;
extern BLOOM_API int SOUND_READYSETPLANT;
extern BLOOM_API int SOUND_DOOMSHROOM;
extern BLOOM_API int SOUND_EXPLOSION;
extern BLOOM_API int SOUND_FINALWAVE;
extern BLOOM_API int SOUND_REVERSE_EXPLOSION;
extern BLOOM_API int SOUND_RVTHROW;
extern BLOOM_API int SOUND_SHIELDHIT;
extern BLOOM_API int SOUND_SHIELDHIT2;
extern BLOOM_API int SOUND_BOSSEXPLOSION;
extern BLOOM_API int SOUND_CHERRYBOMB;
extern BLOOM_API int SOUND_BONK;
extern BLOOM_API int SOUND_SWING;
extern BLOOM_API int SOUND_RAIN;
extern BLOOM_API int SOUND_LIGHTFILL;
extern BLOOM_API int SOUND_PLASTICHIT;
extern BLOOM_API int SOUND_PLASTICHIT2;
extern BLOOM_API int SOUND_JALAPENO;
extern BLOOM_API int SOUND_BALLOONINFLATE;
extern BLOOM_API int SOUND_BIGCHOMP;
extern BLOOM_API int SOUND_MELONIMPACT;
extern BLOOM_API int SOUND_MELONIMPACT2;
extern BLOOM_API int SOUND_PLANTGROW;
extern BLOOM_API int SOUND_SHOOP;
extern BLOOM_API int SOUND_TAPGLASS;
extern BLOOM_API int SOUND_JUICY;
extern BLOOM_API int SOUND_COFFEE;
extern BLOOM_API int SOUND_WAKEUP;
extern BLOOM_API int SOUND_LOWGROAN;
extern BLOOM_API int SOUND_LOWGROAN2;
extern BLOOM_API int SOUND_PRIZE;
extern BLOOM_API int SOUND_YUCK;
extern BLOOM_API int SOUND_YUCK2;
extern BLOOM_API int SOUND_GRASSSTEP;
extern BLOOM_API int SOUND_SHOVEL;
extern BLOOM_API int SOUND_COBLAUNCH;
extern BLOOM_API int SOUND_WATERING;
extern BLOOM_API int SOUND_POLEVAULT;
extern BLOOM_API int SOUND_GRAVESTONE_RUMBLE;
extern BLOOM_API int SOUND_DIRT_RISE;
extern BLOOM_API int SOUND_FERTILIZER;
extern BLOOM_API int SOUND_PORTAL;
extern BLOOM_API int SOUND_BUGSPRAY;
extern BLOOM_API int SOUND_SCREAM;
extern BLOOM_API int SOUND_PAPER;
extern BLOOM_API int SOUND_MONEYFALLS;
extern BLOOM_API int SOUND_IMP;
extern BLOOM_API int SOUND_IMP2;
extern BLOOM_API int SOUND_HYDRAULIC_SHORT;
extern BLOOM_API int SOUND_HYDRAULIC;
extern BLOOM_API int SOUND_GARGANTUDEATH;
extern BLOOM_API int SOUND_CERAMIC;
extern BLOOM_API int SOUND_BOSSBOULDERATTACK;
extern BLOOM_API int SOUND_CHIME;
extern BLOOM_API int SOUND_CRAZYDAVESHORT1;
extern BLOOM_API int SOUND_CRAZYDAVESHORT2;
extern BLOOM_API int SOUND_CRAZYDAVESHORT3;
extern BLOOM_API int SOUND_CRAZYDAVELONG1;
extern BLOOM_API int SOUND_CRAZYDAVELONG2;
extern BLOOM_API int SOUND_CRAZYDAVELONG3;
extern BLOOM_API int SOUND_CRAZYDAVEEXTRALONG1;
extern BLOOM_API int SOUND_CRAZYDAVEEXTRALONG2;
extern BLOOM_API int SOUND_CRAZYDAVEEXTRALONG3;
extern BLOOM_API int SOUND_CRAZYDAVECRAZY;
extern BLOOM_API int SOUND_PHONOGRAPH;
extern BLOOM_API int SOUND_DANCER;
extern BLOOM_API int SOUND_FINALFANFARE;
extern BLOOM_API int SOUND_CRAZYDAVESCREAM;
extern BLOOM_API int SOUND_CRAZYDAVESCREAM2;

extern BLOOM_API void *RESOURCE_NONE;

enum OldResourceId
{
	IMAGE_ALMANAC_INDEXBACK_ID,
	IMAGE_ALMANAC_PLANTBACK_ID,
	IMAGE_ALMANAC_ZOMBIEBACK_ID,
	IMAGE_ALMANAC_PLANTCARD_ID,
	IMAGE_ALMANAC_ZOMBIECARD_ID,
	IMAGE_ALMANAC_ZOMBIEWINDOW_ID,
	IMAGE_ALMANAC_ZOMBIEWINDOW2_ID,
	IMAGE_ALMANAC_ZOMBIEBLANK_ID,
	IMAGE_ALMANAC_GROUNDDAY_ID,
	IMAGE_ALMANAC_GROUNDNIGHT_ID,
	IMAGE_ALMANAC_GROUNDPOOL_ID,
	IMAGE_ALMANAC_GROUNDNIGHTPOOL_ID,
	IMAGE_ALMANAC_GROUNDROOF_ID,
	IMAGE_ALMANAC_GROUNDICE_ID,
	IMAGE_ALMANAC_CLOSEBUTTON_ID,
	IMAGE_ALMANAC_CLOSEBUTTONHIGHLIGHT_ID,
	IMAGE_ALMANAC_INDEXBUTTON_ID,
	IMAGE_ALMANAC_INDEXBUTTONHIGHLIGHT_ID,
	IMAGE_AWARDSCREEN_BACK_ID,
	IMAGE_BACKGROUND1_ID,
	IMAGE_BACKGROUND1_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND1_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND2_ID,
	IMAGE_BACKGROUND2_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND2_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND3_ID,
	IMAGE_BACKGROUND3_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND3_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND4_ID,
	IMAGE_BACKGROUND4_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND4_GAMEOVER_MASK_ID,
	IMAGE_FOG_ID,
	IMAGE_FOG_SOFTWARE_ID,
	IMAGE_BACKGROUND5_ID,
	IMAGE_BACKGROUND5_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND6BOSS_ID,
	IMAGE_BACKGROUND6_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND1UNSODDED_ID,
	IMAGE_SOD1ROW_ID,
	IMAGE_SOD3ROW_ID,
	IMAGE_CHALLENGE_BACKGROUND_ID,
	IMAGE_CHALLENGE_WINDOW_ID,
	IMAGE_CHALLENGE_WINDOW_HIGHLIGHT_ID,
	IMAGE_CHALLENGE_BLANK_ID,
	IMAGE_CHALLENGE_THUMBNAILS_ID,
	IMAGE_SURVIVAL_THUMBNAILS_ID,
	IMAGE_LOCK_ID,
	IMAGE_LOCK_OPEN_ID,
	FONT_BRIANNETOD32_ID,
	FONT_BRIANNETOD32BLACK_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING1_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING2_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING3_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING4_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING5_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_WINK_ID,
	IMAGE_REANIM_CREDITS_DISCOLIGHTS_ID,
	IMAGE_REANIM_CREDITS_FOGMACHINE_ID,
	IMAGE_CREDITS_ZOMBIENOTE_ID,
	IMAGE_CREDITS_PLAYBUTTON_ID,
	IMAGE_BACKGROUND_GREENHOUSE_ID,
	IMAGE_BACKGROUND_GREENHOUSE_OVERLAY_ID,
	IMAGE_BACKGROUND_MUSHROOMGARDEN_ID,
	IMAGE_STORE_BACKGROUND_ID,
	IMAGE_STORE_BACKGROUNDNIGHT_ID,
	IMAGE_STORE_CAR_ID,
	IMAGE_STORE_CAR_NIGHT_ID,
	IMAGE_STORE_CARCLOSED_ID,
	IMAGE_STORE_CARCLOSED_NIGHT_ID,
	IMAGE_STORE_HATCHBACKOPEN_ID,
	IMAGE_STORE_SIGN_ID,
	IMAGE_STORE_MAINMENUBUTTON_ID,
	IMAGE_STORE_MAINMENUBUTTONDOWN_ID,
	IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_ID,
	IMAGE_STORE_NEXTBUTTON_ID,
	IMAGE_STORE_NEXTBUTTONHIGHLIGHT_ID,
	IMAGE_STORE_NEXTBUTTONDISABLED_ID,
	IMAGE_STORE_PREVBUTTON_ID,
	IMAGE_STORE_PREVBUTTONHIGHLIGHT_ID,
	IMAGE_STORE_PREVBUTTONDISABLED_ID,
	IMAGE_STORE_PRICETAG_ID,
	IMAGE_STORE_PACKETUPGRADE_ID,
	IMAGE_STORE_MUSHROOMGARDENICON_ID,
	IMAGE_STORE_AQUARIUMGARDENICON_ID,
	IMAGE_STORE_TREEOFWISDOMICON_ID,
	IMAGE_STORE_FIRSTAIDWALLNUTICON_ID,
	IMAGE_STORE_PVZICON_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BG_ID,
	IMAGE_ZOMBATAR_PREV_BUTTON_ID,
	IMAGE_ZOMBATAR_PREV_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_NEXT_BUTTON_ID,
	IMAGE_ZOMBATAR_NEXT_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_ZOMBIE_BLANK_ID,
	IMAGE_ZOMBATAR_ZOMBIE_BLANK_SKIN_ID,
	IMAGE_ZOMBATAR_BACKGROUND_CRAZYDAVE_ID,
	IMAGE_ZOMBATAR_BACKGROUND_MENU_ID,
	IMAGE_ZOMBATAR_BACKGROUND_MENU_DOS_ID,
	IMAGE_ZOMBATAR_BACKGROUND_ROOF_ID,
	IMAGE_ZOMBATAR_WIDGET_BG_ID,
	IMAGE_ZOMBATAR_WIDGET_INNER_BG_ID,
	IMAGE_ZOMBATAR_COLORS_BG_ID,
	IMAGE_ZOMBATAR_LOGO_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BUTTON_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_BACKDROPS_BUTTON_ID,
	IMAGE_ZOMBATAR_BACKDROPS_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_BACKDROPS_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_CLOTHES_BUTTON_ID,
	IMAGE_ZOMBATAR_CLOTHES_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_CLOTHES_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_EYEWEAR_BUTTON_ID,
	IMAGE_ZOMBATAR_EYEWEAR_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_EYEWEAR_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_ID,
	IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_HAIR_BUTTON_ID,
	IMAGE_ZOMBATAR_HAIR_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_HAIR_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_HATS_BUTTON_ID,
	IMAGE_ZOMBATAR_HATS_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_HATS_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_SKIN_BUTTON_ID,
	IMAGE_ZOMBATAR_SKIN_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TIDBITS_BUTTON_ID,
	IMAGE_ZOMBATAR_TIDBITS_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TIDBITS_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BG_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TRIPTYCH_ID,
	IMAGE_ZOMBATAR_COLORPICKER_ID,
	IMAGE_ZOMBATAR_COLORPICKER_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_COLORPICKER_NONE_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BG_NONE_ID,
	IMAGE_ZOMBATAR_COLORS_BG_SMALL_ID,
	IMAGE_ZOMBATAR_CLOTHES_1_ID,
	IMAGE_ZOMBATAR_CLOTHES_2_ID,
	IMAGE_ZOMBATAR_CLOTHES_3_ID,
	IMAGE_ZOMBATAR_CLOTHES_4_ID,
	IMAGE_ZOMBATAR_CLOTHES_5_ID,
	IMAGE_ZOMBATAR_CLOTHES_6_ID,
	IMAGE_ZOMBATAR_CLOTHES_7_ID,
	IMAGE_ZOMBATAR_CLOTHES_8_ID,
	IMAGE_ZOMBATAR_CLOTHES_9_ID,
	IMAGE_ZOMBATAR_CLOTHES_10_ID,
	IMAGE_ZOMBATAR_CLOTHES_11_ID,
	IMAGE_ZOMBATAR_CLOTHES_12_ID,
	IMAGE_ZOMBATAR_HATS_1_ID,
	IMAGE_ZOMBATAR_HATS_2_ID,
	IMAGE_ZOMBATAR_HATS_3_ID,
	IMAGE_ZOMBATAR_HATS_4_ID,
	IMAGE_ZOMBATAR_HATS_5_ID,
	IMAGE_ZOMBATAR_HATS_6_ID,
	IMAGE_ZOMBATAR_HATS_7_ID,
	IMAGE_ZOMBATAR_HATS_8_ID,
	IMAGE_ZOMBATAR_HATS_9_ID,
	IMAGE_ZOMBATAR_HATS_10_ID,
	IMAGE_ZOMBATAR_HATS_11_ID,
	IMAGE_ZOMBATAR_HATS_12_ID,
	IMAGE_ZOMBATAR_HATS_13_ID,
	IMAGE_ZOMBATAR_HATS_14_ID,
	IMAGE_ZOMBATAR_HAIR_1_ID,
	IMAGE_ZOMBATAR_HAIR_2_ID,
	IMAGE_ZOMBATAR_HAIR_3_ID,
	IMAGE_ZOMBATAR_HAIR_4_ID,
	IMAGE_ZOMBATAR_HAIR_5_ID,
	IMAGE_ZOMBATAR_HAIR_6_ID,
	IMAGE_ZOMBATAR_HAIR_7_ID,
	IMAGE_ZOMBATAR_HAIR_8_ID,
	IMAGE_ZOMBATAR_HAIR_9_ID,
	IMAGE_ZOMBATAR_HAIR_10_ID,
	IMAGE_ZOMBATAR_HAIR_11_ID,
	IMAGE_ZOMBATAR_HAIR_12_ID,
	IMAGE_ZOMBATAR_HAIR_13_ID,
	IMAGE_ZOMBATAR_HAIR_14_ID,
	IMAGE_ZOMBATAR_HAIR_15_ID,
	IMAGE_ZOMBATAR_HAIR_16_ID,
	IMAGE_ZOMBATAR_EYEWEAR_1_ID,
	IMAGE_ZOMBATAR_EYEWEAR_2_ID,
	IMAGE_ZOMBATAR_EYEWEAR_3_ID,
	IMAGE_ZOMBATAR_EYEWEAR_4_ID,
	IMAGE_ZOMBATAR_EYEWEAR_5_ID,
	IMAGE_ZOMBATAR_EYEWEAR_6_ID,
	IMAGE_ZOMBATAR_EYEWEAR_7_ID,
	IMAGE_ZOMBATAR_EYEWEAR_8_ID,
	IMAGE_ZOMBATAR_EYEWEAR_9_ID,
	IMAGE_ZOMBATAR_EYEWEAR_10_ID,
	IMAGE_ZOMBATAR_EYEWEAR_11_ID,
	IMAGE_ZOMBATAR_EYEWEAR_12_ID,
	IMAGE_ZOMBATAR_EYEWEAR_13_ID,
	IMAGE_ZOMBATAR_EYEWEAR_14_ID,
	IMAGE_ZOMBATAR_EYEWEAR_15_ID,
	IMAGE_ZOMBATAR_EYEWEAR_16_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_1_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_2_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_3_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_4_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_5_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_6_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_7_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_8_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_9_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_10_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_11_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_12_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_13_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_14_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_15_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_16_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_17_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_18_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_19_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_20_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_21_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_22_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_23_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_24_ID,
	IMAGE_ZOMBATAR_TIDBITS_1_ID,
	IMAGE_ZOMBATAR_TIDBITS_2_ID,
	IMAGE_ZOMBATAR_TIDBITS_3_ID,
	IMAGE_ZOMBATAR_TIDBITS_4_ID,
	IMAGE_ZOMBATAR_TIDBITS_5_ID,
	IMAGE_ZOMBATAR_TIDBITS_6_ID,
	IMAGE_ZOMBATAR_TIDBITS_7_ID,
	IMAGE_ZOMBATAR_TIDBITS_8_ID,
	IMAGE_ZOMBATAR_TIDBITS_9_ID,
	IMAGE_ZOMBATAR_TIDBITS_10_ID,
	IMAGE_ZOMBATAR_TIDBITS_11_ID,
	IMAGE_ZOMBATAR_TIDBITS_12_ID,
	IMAGE_ZOMBATAR_TIDBITS_13_ID,
	IMAGE_ZOMBATAR_TIDBITS_14_ID,
	IMAGE_ZOMBATAR_ACCESSORY_1_ID,
	IMAGE_ZOMBATAR_ACCESSORY_2_ID,
	IMAGE_ZOMBATAR_ACCESSORY_3_ID,
	IMAGE_ZOMBATAR_ACCESSORY_4_ID,
	IMAGE_ZOMBATAR_ACCESSORY_5_ID,
	IMAGE_ZOMBATAR_ACCESSORY_6_ID,
	IMAGE_ZOMBATAR_ACCESSORY_7_ID,
	IMAGE_ZOMBATAR_ACCESSORY_8_ID,
	IMAGE_ZOMBATAR_ACCESSORY_9_ID,
	IMAGE_ZOMBATAR_ACCESSORY_10_ID,
	IMAGE_ZOMBATAR_ACCESSORY_11_ID,
	IMAGE_ZOMBATAR_ACCESSORY_12_ID,
	IMAGE_ZOMBATAR_ACCESSORY_13_ID,
	IMAGE_ZOMBATAR_ACCESSORY_14_ID,
	IMAGE_ZOMBATAR_HATS_1_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_1_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_2_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_11_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_12_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_13_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_14_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_15_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_1_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_4_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_8_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_9_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_10_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_11_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_12_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_14_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_15_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_16_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_18_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_21_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_22_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_23_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_24_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_1_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_2_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_3_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_4_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_5_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_6_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_7_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_8_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_9_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_10_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_11_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_12_MASK_ID,
	IMAGE_ZOMBATAR_HATS_3_MASK_ID,
	IMAGE_ZOMBATAR_HATS_6_MASK_ID,
	IMAGE_ZOMBATAR_HATS_7_MASK_ID,
	IMAGE_ZOMBATAR_HATS_8_MASK_ID,
	IMAGE_ZOMBATAR_HATS_9_MASK_ID,
	IMAGE_ZOMBATAR_HATS_11_MASK_ID,
	IMAGE_ZOMBATAR_BACKGROUND_BLANK_ID,
	IMAGE_ZOMBATAR_ACCESSORY_15_ID,
	IMAGE_ZOMBATAR_ACCESSORY_16_ID,
	IMAGE_ZOMBATAR_ACCEPT_BUTTON_ID,
	IMAGE_ZOMBATAR_ACCEPT_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_FINISHED_BUTTON_ID,
	IMAGE_ZOMBATAR_FINISHED_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_MAIN_BG_ID,
	IMAGE_ZOMBATAR_BACK_BUTTON_ID,
	IMAGE_ZOMBATAR_BACK_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_ID,
	IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TOS_ARROW_ID,
	IMAGE_ZOMBATAR_BEGIN_BUTTON_ID,
	IMAGE_ZOMBATAR_BEGIN_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TOS_SLIDER_ID,
	IMAGE_ZOMBATAR_TOS_SLIDER_THUMB_ID,
	IMAGE_ZOMBATAR_DISPLAY_WINDOW_ID,
	IMAGE_ZOMBATAR_MAINMENUBACK_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_VIEW_BUTTON_ID,
	IMAGE_ZOMBATAR_VIEW_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBIE_FINAL_NOTE_ID,
	IMAGE_ZOMBIE_NOTE_ID,
	IMAGE_ZOMBIE_NOTE1_ID,
	IMAGE_ZOMBIE_NOTE2_ID,
	IMAGE_ZOMBIE_NOTE3_ID,
	IMAGE_ZOMBIE_NOTE4_ID,
	IMAGE_ZOMBIE_NOTE_HELP_ID,
	IMAGE_AQUARIUM1_ID,
	IMAGE_WAVECENTER_ID,
	IMAGE_WAVESIDE_ID,
	IMAGE_BLANK_ID,
	IMAGE_POPCAP_LOGO_ID,
	IMAGE_PARTNER_LOGO_ID,
	IMAGE_TITLESCREEN_ID,
	IMAGE_LOADBAR_DIRT_ID,
	IMAGE_LOADBAR_GRASS_ID,
	IMAGE_PVZ_LOGO_ID,
	IMAGE_REANIM_SODROLLCAP_ID,
	FONT_BRIANNETOD16_ID,
	SOUND_BUTTONCLICK_ID,
	SOUND_LOADINGBAR_FLOWER_ID,
	SOUND_LOADINGBAR_ZOMBIE_ID,
	FONT_IMAGE_HOUSEOFTERROR28_ID,
	FONT_HOUSEOFTERROR28_ID,
	FONT_HOUSEOFTERROR20_ID,
	FONT_HOUSEOFTERROR16_ID,
	FONT_TINYBOLD_ID,
	FONT_CONTINUUMBOLD14_ID,
	FONT_CONTINUUMBOLD14OUTLINE_ID,
	FONT_DWARVENTODCRAFT12_ID,
	FONT_DWARVENTODCRAFT15_ID,
	FONT_DWARVENTODCRAFT18_ID,
	FONT_DWARVENTODCRAFT18BRIGHTGREENINSET_ID,
	FONT_DWARVENTODCRAFT18GREENINSET_ID,
	FONT_DWARVENTODCRAFT18YELLOW_ID,
	FONT_DWARVENTODCRAFT24_ID,
	FONT_DWARVENTODCRAFT36BRIGHTGREENINSET_ID,
	FONT_DWARVENTODCRAFT36GREENINSET_ID,
	FONT_PICO129_ID,
	FONT_BRIANNETOD12_ID,
	IMAGE_EDITBOX_ID,
	IMAGE_DIALOG_TOPLEFT_ID,
	IMAGE_DIALOG_TOPMIDDLE_ID,
	IMAGE_DIALOG_TOPRIGHT_ID,
	IMAGE_DIALOG_CENTERLEFT_ID,
	IMAGE_DIALOG_CENTERMIDDLE_ID,
	IMAGE_DIALOG_CENTERRIGHT_ID,
	IMAGE_DIALOG_BOTTOMLEFT_ID,
	IMAGE_DIALOG_BOTTOMMIDDLE_ID,
	IMAGE_DIALOG_BOTTOMRIGHT_ID,
	IMAGE_DIALOG_BIGBOTTOMLEFT_ID,
	IMAGE_DIALOG_BIGBOTTOMMIDDLE_ID,
	IMAGE_DIALOG_BIGBOTTOMRIGHT_ID,
	IMAGE_DIALOG_HEADER_ID,
	IMAGE_BUTTON_LEFT_ID,
	IMAGE_BUTTON_MIDDLE_ID,
	IMAGE_BUTTON_RIGHT_ID,
	IMAGE_BUTTON_DOWN_LEFT_ID,
	IMAGE_BUTTON_DOWN_MIDDLE_ID,
	IMAGE_BUTTON_DOWN_RIGHT_ID,
	IMAGE_SEEDCHOOSER_BACKGROUND_ID,
	IMAGE_SEEDCHOOSER_BUTTON_ID,
	IMAGE_SEEDCHOOSER_BUTTON_DISABLED_ID,
	IMAGE_SEEDCHOOSER_BUTTON_GLOW_ID,
	IMAGE_SEEDCHOOSER_BUTTON2_ID,
	IMAGE_SEEDCHOOSER_BUTTON2_GLOW_ID,
	IMAGE_SEEDCHOOSER_IMITATERADDON_ID,
	IMAGE_SEEDS_ID,
	IMAGE_SEEDPACKET_LARGER_ID,
	IMAGE_SEEDPACKETSILHOUETTE_ID,
	IMAGE_FLAGMETER_ID,
	IMAGE_FLAGMETERLEVELPROGRESS_ID,
	IMAGE_FLAGMETERPARTS_ID,
	IMAGE_TROPHY_ID,
	IMAGE_TROPHY_HI_RES_ID,
	IMAGE_MINIGAME_TROPHY_ID,
	IMAGE_ZOMBIE_NOTE_SMALL_ID,
	IMAGE_TACO_ID,
	IMAGE_CARKEYS_ID,
	IMAGE_ALMANAC_ID,
	IMAGE_ICON_POOLCLEANER_ID,
	IMAGE_ICON_ROOFCLEANER_ID,
	IMAGE_ICON_RAKE_ID,
	IMAGE_BRAIN_ID,
	IMAGE_MONEYBAG_ID,
	IMAGE_MONEYBAG_HI_RES_ID,
	IMAGE_CHOCOLATE_ID,
	IMAGE_OPTIONS_BACKTOGAMEBUTTON0_ID,
	IMAGE_OPTIONS_BACKTOGAMEBUTTON2_ID,
	IMAGE_OPTIONS_CHECKBOX0_ID,
	IMAGE_OPTIONS_CHECKBOX1_ID,
	IMAGE_OPTIONS_MENUBACK_ID,
	IMAGE_OPTIONS_SLIDERKNOB2_ID,
	IMAGE_OPTIONS_SLIDERSLOT_ID,
	IMAGE_SELECTORSCREEN_HELP1_ID,
	IMAGE_SELECTORSCREEN_HELP2_ID,
	IMAGE_SELECTORSCREEN_OPTIONS1_ID,
	IMAGE_SELECTORSCREEN_OPTIONS2_ID,
	IMAGE_SELECTORSCREEN_QUIT1_ID,
	IMAGE_SELECTORSCREEN_QUIT2_ID,
	IMAGE_SELECTORSCREEN_ALMANAC_ID,
	IMAGE_SELECTORSCREEN_ALMANACHIGHLIGHT_ID,
	IMAGE_SELECTORSCREEN_STORE_ID,
	IMAGE_SELECTORSCREEN_STOREHIGHLIGHT_ID,
	IMAGE_SELECTORSCREEN_LEVELNUMBERS_ID,
	IMAGE_SELECTORSCREEN_ZENGARDEN_ID,
	IMAGE_SELECTORSCREEN_ZENGARDENHIGHLIGHT_ID,
	IMAGE_STORE_SPEECHBUBBLE_ID,
	IMAGE_STORE_SPEECHBUBBLE2_ID,
	IMAGE_SELECTORSCREEN_ACHIEVEMENTS_BG_ID,
	IMAGE_SELECTORSCREEN_MOREWAYSTOPLAY_BG_ID,
	IMAGE_SELECTORSCREEN_ACHIEVEMENTS_PEDESTAL_ID,
	IMAGE_SELECTORSCREEN_ACHIEVEMENTS_PEDESTAL_PRESS_ID,
	IMAGE_ACHEESEMENTS_BEJEWELED_ID,
	IMAGE_ACHEESEMENTS_BOOKWORM_ID,
	IMAGE_ACHEESEMENTS_CHINA_ID,
	IMAGE_ACHEESEMENTS_CHUZZLE_ID,
	IMAGE_ACHEESEMENTS_HOLE_TILE_ID,
	IMAGE_ACHEESEMENTS_PEGGLE_ID,
	IMAGE_ACHEESEMENTS_PIPE_ID,
	IMAGE_ACHEESEMENTS_ZUMA_ID,
	IMAGE_ACHEESEMENTS_ICONS_ID,
	IMAGE_ACHEESEMENTS_BACK_HIGHLIGHT_ID,
	IMAGE_QUICKPLAY_MINIGAMES_BUTTON_ID,
	IMAGE_QUICKPLAY_MINIGAMES_BUTTON_HIGHLIGHT_ID,
	IMAGE_QUICKPLAY_MINIGAMES_CLOUD_ID,
	IMAGE_QUICKPLAY_PUZZLES_BUTTON_ID,
	IMAGE_QUICKPLAY_PUZZLES_BUTTON_HIGHLIGHT_ID,
	IMAGE_QUICKPLAY_PUZZLES_CLOUD_ID,
	IMAGE_QUICKPLAY_SURVIVAL_BUTTON_ID,
	IMAGE_QUICKPLAY_SURVIVAL_BUTTON_HIGHLIGHT_ID,
	IMAGE_QUICKPLAY_SURVIVAL_CLOUD_ID,
	IMAGE_QUICKPLAY_BACK_BUTTON_ID,
	IMAGE_QUICKPLAY_BACK_BUTTON_HIGHLIGHT_ID,
	IMAGE_ACHEESEMENTS_MORE_ROCK_ID,
	IMAGE_ACHEESEMENTS_MORE_BUTTON_ID,
	IMAGE_ACHEESEMENTS_MORE_BUTTON_HIGHLIGHT_ID,
	IMAGE_ACHEESEMENTS_TOP_BUTTON_ID,
	IMAGE_ACHEESEMENTS_TOP_BUTTON_HIGHLIGHT_ID,
	IMAGE_SHOVEL_ID,
	IMAGE_SHOVEL_HI_RES_ID,
	IMAGE_TOMBSTONES_ID,
	IMAGE_TOMBSTONE_MOUNDS_ID,
	IMAGE_NIGHT_GRAVE_GRAPHIC_ID,
	IMAGE_CRATER_ID,
	IMAGE_CRATER_FADING_ID,
	IMAGE_CRATER_ROOF_CENTER_ID,
	IMAGE_CRATER_ROOF_LEFT_ID,
	IMAGE_CRATER_WATER_DAY_ID,
	IMAGE_CRATER_WATER_NIGHT_ID,
	IMAGE_COBCANNON_TARGET_ID,
	IMAGE_COBCANNON_POPCORN_ID,
	IMAGE_FERTILIZER_ID,
	IMAGE_WATERINGCAN_ID,
	IMAGE_WATERINGCANGOLD_ID,
	IMAGE_PHONOGRAPH_ID,
	IMAGE_BEGHOULED_TWIST_OVERLAY_ID,
	IMAGE_ZEN_GOLDTOOLRETICLE_ID,
	IMAGE_ZEN_GARDENGLOVE_ID,
	IMAGE_ZEN_MONEYSIGN_ID,
	IMAGE_ZEN_NEXTGARDEN_ID,
	IMAGE_ZEN_WHEELBARROW_ID,
	IMAGE_ZENSHOPBUTTON_ID,
	IMAGE_ZENSHOPBUTTON_HIGHLIGHT_ID,
	IMAGE_PRESENT_ID,
	IMAGE_PRESENTOPEN_ID,
	IMAGE_SUNFLOWER_TROPHY_ID,
	IMAGE_SLOTMACHINE_OVERLAY_ID,
	IMAGE_SCARY_POT_ID,
	IMAGE_BUG_SPRAY_ID,
	IMAGE_PLANTSPEECHBUBBLE_ID,
	IMAGE_WATERDROP_ID,
	IMAGE_TREEFOOD_ID,
	IMAGE_PACKET_PLANTS_ID,
	IMAGE_ZEN_NEED_ICONS_ID,
	IMAGE_PROJECTILEPEA_ID,
	IMAGE_PROJECTILESNOWPEA_ID,
	IMAGE_PROJECTILECACTUS_ID,
	IMAGE_DIRTSMALL_ID,
	IMAGE_DIRTBIG_ID,
	IMAGE_ROCKSMALL_ID,
	IMAGE_WATERPARTICLE_ID,
	IMAGE_WHITEWATER_ID,
	IMAGE_WHITEWATER_SHADOW_ID,
	IMAGE_MELONPULT_PARTICLES_ID,
	IMAGE_WINTERMELON_PARTICLES_ID,
	IMAGE_PROJECTILE_STAR_ID,
	IMAGE_SEEDBANK_ID,
	IMAGE_CONVEYORBELT_BACKDROP_ID,
	IMAGE_CONVEYORBELT_ID,
	IMAGE_SHOVELBANK_ID,
	IMAGE_SUNBANK_ID,
	IMAGE_COINBANK_ID,
	IMAGE_POOL_ID,
	IMAGE_POOL_NIGHT_ID,
	IMAGE_POOL_BASE_ID,
	IMAGE_POOL_BASE_NIGHT_ID,
	IMAGE_POOL_SHADING_ID,
	IMAGE_POOL_SHADING_NIGHT_ID,
	IMAGE_POOL_CAUSTIC_EFFECT_ID,
	IMAGE_PLANTSHADOW_ID,
	IMAGE_PLANTSHADOW2_ID,
	IMAGE_PEA_SHADOWS_ID,
	IMAGE_WALLNUT_BOWLINGSTRIPE_ID,
	IMAGE_ICE_ID,
	IMAGE_ICE_CAP_ID,
	IMAGE_ICE_SPARKLES_ID,
	IMAGE_IMITATERSEED_ID,
	IMAGE_ALMANAC_IMITATER_ID,
	IMAGE_IMITATERSEEDDISABLED_ID,
	IMAGE_ICETRAP_ID,
	IMAGE_ICETRAP2_ID,
	IMAGE_ICETRAP_PARTICLES_ID,
	IMAGE_ZOMBIE_BOBSLED1_ID,
	IMAGE_ZOMBIE_BOBSLED2_ID,
	IMAGE_ZOMBIE_BOBSLED3_ID,
	IMAGE_ZOMBIE_BOBSLED4_ID,
	IMAGE_ZOMBIE_BOBSLED_INSIDE_ID,
	IMAGE_BUNGEECORD_ID,
	IMAGE_BUNGEETARGET_ID,
	IMAGE_SPOTLIGHT_ID,
	IMAGE_SPOTLIGHT2_ID,
	IMAGE_WHITEPIXEL_ID,
	IMAGE_ZOMBIEPOLEVAULTERHEAD_ID,
	IMAGE_ZOMBIEFOOTBALLHEAD_ID,
	IMAGE_POOLSPARKLY_ID,
	IMAGE_WALLNUTPARTICLESSMALL_ID,
	IMAGE_WALLNUTPARTICLESLARGE_ID,
	IMAGE_PEA_SPLATS_ID,
	IMAGE_STAR_PARTICLES_ID,
	IMAGE_STAR_SPLATS_ID,
	IMAGE_PEA_PARTICLES_ID,
	IMAGE_SNOWPEA_SPLATS_ID,
	IMAGE_SNOWPEA_PARTICLES_ID,
	IMAGE_SNOWPEA_PUFF_ID,
	IMAGE_SNOWFLAKES_ID,
	IMAGE_POTATOMINE_PARTICLES_ID,
	IMAGE_PUFFSHROOM_PUFF1_ID,
	IMAGE_ZAMBONISMOKE_ID,
	IMAGE_ZOMBIEDANCERHEAD_ID,
	IMAGE_ZOMBIEBALLOONHEAD_ID,
	IMAGE_ZOMBIEIMPHEAD_ID,
	IMAGE_ZOMBIEDIGGERHEAD_ID,
	IMAGE_ZOMBIEDIGGERARM_ID,
	IMAGE_ZOMBIEDOLPHINRIDERHEAD_ID,
	IMAGE_ZOMBIEPOGO_ID,
	IMAGE_ZOMBIEBACKUPDANCERHEAD_ID,
	IMAGE_ZOMBIEBOBSLEDHEAD_ID,
	IMAGE_ZOMBIELADDERHEAD_ID,
	IMAGE_ZOMBIEYETIHEAD_ID,
	IMAGE_SEEDPACKETFLASH_ID,
	IMAGE_ZOMBIEJACKBOXARM_ID,
	IMAGE_IMITATERCLOUDS_ID,
	IMAGE_IMITATERPUFFS_ID,
	IMAGE_ZOMBIE_BOSS_FIREBALL_PARTICLES_ID,
	IMAGE_ZOMBIE_BOSS_ICEBALL_PARTICLES_ID,
	IMAGE_ZOMBIE_BOSS_FIREBALL_GROUNDPARTICLES_ID,
	IMAGE_ZOMBIE_BOSS_ICEBALL_GROUNDPARTICLES_ID,
	IMAGE_DOOMSHROOM_EXPLOSION_BASE_ID,
	IMAGE_RAIN_ID,
	IMAGE_VASE_CHUNKS_ID,
	IMAGE_ZOMBOSS_PARTICLES_ID,
	IMAGE_AWARDPICKUPGLOW_ID,
	IMAGE_ZOMBIE_SEAWEED_ID,
	IMAGE_PINATA_ID,
	IMAGE_ZOMBIEFUTUREGLASSES_ID,
	IMAGE_DUST_PUFFS_ID,
	IMAGE_REANIM_WALLNUT_BODY_ID,
	IMAGE_REANIM_WALLNUT_CRACKED1_ID,
	IMAGE_REANIM_WALLNUT_CRACKED2_ID,
	IMAGE_REANIM_TALLNUT_CRACKED1_ID,
	IMAGE_REANIM_TALLNUT_CRACKED2_ID,
	IMAGE_REANIM_PUMPKIN_DAMAGE1_ID,
	IMAGE_REANIM_PUMPKIN_DAMAGE3_ID,
	IMAGE_REANIM_ZOMBIE_CONE1_ID,
	IMAGE_REANIM_ZOMBIE_CONE2_ID,
	IMAGE_REANIM_ZOMBIE_CONE3_ID,
	IMAGE_REANIM_ZOMBIE_BUCKET1_ID,
	IMAGE_REANIM_ZOMBIE_BUCKET2_ID,
	IMAGE_REANIM_ZOMBIE_BUCKET3_ID,
	IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT_ID,
	IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT2_ID,
	IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT3_ID,
	IMAGE_REANIM_ZOMBIE_SCREENDOOR1_ID,
	IMAGE_REANIM_ZOMBIE_SCREENDOOR2_ID,
	IMAGE_REANIM_ZOMBIE_SCREENDOOR3_ID,
	IMAGE_REANIM_ZOMBIE_FLAG1_ID,
	IMAGE_REANIM_ZOMBIE_FLAG3_ID,
	IMAGE_REANIM_ZOMBIE_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET_ID,
	IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET2_ID,
	IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET3_ID,
	IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_HAND_ID,
	IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_LOWER_ID,
	IMAGE_REANIM_ZOMBIE_PAPER_PAPER2_ID,
	IMAGE_REANIM_ZOMBIE_PAPER_PAPER3_ID,
	IMAGE_REANIM_ZOMBIE_PAPER_MADHEAD_ID,
	IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_ZAMBONI_WHEEL_FLAT_ID,
	IMAGE_REANIM_COIN_SILVER_DOLLAR_ID,
	IMAGE_REANIM_COIN_GOLD_DOLLAR_ID,
	IMAGE_REANIM_DIAMOND_ID,
	IMAGE_REANIM_COINGLOW_ID,
	IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_HAND_ID,
	IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_BACKUP_INNERARM_HAND_ID,
	IMAGE_REANIM_ZOMBIE_BACKUP_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_POLEVAULTER_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_OUTERARM_HAND_ID,
	IMAGE_REANIM_ZOMBIE_BALLOON_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_IMP_ARM1_BONE_ID,
	IMAGE_REANIM_ZOMBIE_IMP_ARM2_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_2_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_3_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_DUCKXING_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_ZOMBIE_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_FOOT2_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_OUTERARM_LOWER2_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2_REDEYE_ID,
	IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD_REDEYE_ID,
	IMAGE_REANIM_ZOMBIE_DIGGER_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_DOLPHINRIDER_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_POGO_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_POGO_STICKHANDS2_ID,
	IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_HAND_ID,
	IMAGE_REANIM_ZOMBIE_JACKBOX_BOX_ID,
	IMAGE_REANIM_ZOMBIE_JACKBOX_OUTERARM_LOWER2_ID,
	IMAGE_REANIM_ZOMBIE_SNORKLE_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_BUNGI_HEAD_SCARED_ID,
	IMAGE_REANIM_ZOMBIE_CATAPULT_BASKETBALL_ID,
	IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_ID,
	IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE_ID,
	IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_WITHBALL_ID,
	IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE_WITHBALL_ID,
	IMAGE_REANIM_ZOMBIE_CATAPULT_SIDING_DAMAGE_ID,
	IMAGE_REANIM_ZOMBIE_LADDER_1_ID,
	IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_LADDER_5_ID,
	IMAGE_REANIM_ZOMBIE_LADDER_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_ICEBALL_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE1_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE2_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_EYEGLOW_BLUE_ID,
	IMAGE_REANIM_ZOMBIE_BOSS_MOUTHGLOW_BLUE_ID,
	IMAGE_REANIM_CABBAGEPULT_CABBAGE_ID,
	IMAGE_REANIM_CORNPULT_KERNAL_ID,
	IMAGE_REANIM_CORNPULT_BUTTER_ID,
	IMAGE_REANIM_CORNPULT_BUTTER_SPLAT_ID,
	IMAGE_REANIM_MELONPULT_MELON_ID,
	IMAGE_REANIM_WINTERMELON_PROJECTILE_ID,
	IMAGE_REANIM_ZOMBIE_DIGGER_PICKAXE_ID,
	IMAGE_REANIM_ZOMBIE_HEAD_GROSSOUT_ID,
	IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES1_ID,
	IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES2_ID,
	IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES3_ID,
	IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES4_ID,
	IMAGE_REANIM_GARLIC_BODY2_ID,
	IMAGE_REANIM_GARLIC_BODY3_ID,
	IMAGE_REANIM_COBCANNON_COB_ID,
	IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_UPPER2_ID,
	IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_HAND_ID,
	IMAGE_REANIM_ZOMBIE_SNORKLE_HEAD_ID,
	IMAGE_REANIM_SELECTORSCREEN_ADVENTURE_BUTTON_ID,
	IMAGE_REANIM_SELECTORSCREEN_ADVENTURE_HIGHLIGHT_ID,
	IMAGE_REANIM_SELECTORSCREEN_STARTADVENTURE_BUTTON_ID,
	IMAGE_REANIM_SELECTORSCREEN_STARTADVENTURE_HIGHLIGHT_ID,
	IMAGE_REANIM_SELECTORSCREEN_SURVIVAL_BUTTON_ID,
	IMAGE_REANIM_SELECTORSCREEN_SURVIVAL_HIGHLIGHT_ID,
	IMAGE_REANIM_SELECTORSCREEN_CHALLENGES_BUTTON_ID,
	IMAGE_REANIM_SELECTORSCREEN_CHALLENGES_HIGHLIGHT_ID,
	IMAGE_REANIM_SELECTORSCREEN_VASEBREAKER_BUTTON_ID,
	IMAGE_REANIM_SELECTORSCREEN_VASEBREAKER_HIGHLIGHT_ID,
	IMAGE_REANIM_SELECTORSCREEN_WOODSIGN2_PRESS_ID,
	IMAGE_REANIM_SELECTORSCREEN_WOODSIGN3_PRESS_ID,
	IMAGE_REANIM_SELECTORSCREEN_BG_ID,
	IMAGE_REANIM_SELECTORSCREEN_ALMANAC_SHADOW_ID,
	IMAGE_REANIM_SELECTORSCREEN_KEY_SHADOW_ID,
	IMAGE_REANIM_TREE_BG_ID,
	IMAGE_REANIM_POT_TOP_DARK_ID,
	IMAGE_REANIM_ZENGARDEN_BUGSPRAY_BOTTLE_ID,
	IMAGE_REANIM_STINKY_TURN3_ID,
	IMAGE_REANIM_CRAZYDAVE_MOUTH1_ID,
	IMAGE_REANIM_CRAZYDAVE_MOUTH4_ID,
	IMAGE_REANIM_CRAZYDAVE_MOUTH5_ID,
	IMAGE_REANIM_CRAZYDAVE_MOUTH6_ID,
	IMAGE_REANIM_ZOMBIE_MUSTACHE2_ID,
	IMAGE_REANIM_ZOMBIE_MUSTACHE3_ID,
	SOUND_ACHIEVEMENT_ID,
	SOUND_AWOOGA_ID,
	SOUND_BLEEP_ID,
	SOUND_BUZZER_ID,
	SOUND_CHOMP_ID,
	SOUND_CHOMP2_ID,
	SOUND_CHOMPSOFT_ID,
	SOUND_EVILLAUGH_ID,
	SOUND_FLOOP_ID,
	SOUND_FROZEN_ID,
	SOUND_GULP_ID,
	SOUND_GROAN_ID,
	SOUND_GROAN2_ID,
	SOUND_GROAN3_ID,
	SOUND_GROAN4_ID,
	SOUND_GROAN5_ID,
	SOUND_GROAN6_ID,
	SOUND_LOSEMUSIC_ID,
	SOUND_MINDCONTROLLED_ID,
	SOUND_PAUSE_ID,
	SOUND_PLANT_ID,
	SOUND_PLANT2_ID,
	SOUND_POINTS_ID,
	SOUND_SEEDLIFT_ID,
	SOUND_SIREN_ID,
	SOUND_SLURP_ID,
	SOUND_SPLAT_ID,
	SOUND_SPLAT2_ID,
	SOUND_SPLAT3_ID,
	SOUND_SUKHBIR_ID,
	SOUND_SUKHBIR2_ID,
	SOUND_SUKHBIR3_ID,
	SOUND_SUKHBIR4_ID,
	SOUND_SUKHBIR5_ID,
	SOUND_SUKHBIR6_ID,
	SOUND_TAP_ID,
	SOUND_TAP2_ID,
	SOUND_THROW_ID,
	SOUND_THROW2_ID,
	SOUND_BLOVER_ID,
	SOUND_WINMUSIC_ID,
	SOUND_LAWNMOWER_ID,
	SOUND_BOING_ID,
	SOUND_JACKINTHEBOX_ID,
	SOUND_DIAMOND_ID,
	SOUND_DOLPHIN_APPEARS_ID,
	SOUND_DOLPHIN_BEFORE_JUMPING_ID,
	SOUND_POTATO_MINE_ID,
	SOUND_ZAMBONI_ID,
	SOUND_BALLOON_POP_ID,
	SOUND_THUNDER_ID,
	SOUND_ZOMBIESPLASH_ID,
	SOUND_BOWLING_ID,
	SOUND_BOWLINGIMPACT_ID,
	SOUND_BOWLINGIMPACT2_ID,
	SOUND_GRAVEBUSTERCHOMP_ID,
	SOUND_GRAVEBUTTON_ID,
	SOUND_LIMBS_POP_ID,
	SOUND_PLANTERN_ID,
	SOUND_POGO_ZOMBIE_ID,
	SOUND_SNOW_PEA_SPARKLES_ID,
	SOUND_PLANT_WATER_ID,
	SOUND_ZOMBIE_ENTERING_WATER_ID,
	SOUND_ZOMBIE_FALLING_1_ID,
	SOUND_ZOMBIE_FALLING_2_ID,
	SOUND_PUFF_ID,
	SOUND_FUME_ID,
	SOUND_HUGE_WAVE_ID,
	SOUND_SLOT_MACHINE_ID,
	SOUND_COIN_ID,
	SOUND_ROLL_IN_ID,
	SOUND_DIGGER_ZOMBIE_ID,
	SOUND_HATCHBACK_CLOSE_ID,
	SOUND_HATCHBACK_OPEN_ID,
	SOUND_KERNELPULT_ID,
	SOUND_KERNELPULT2_ID,
	SOUND_ZOMBAQUARIUM_DIE_ID,
	SOUND_BUNGEE_SCREAM_ID,
	SOUND_BUNGEE_SCREAM2_ID,
	SOUND_BUNGEE_SCREAM3_ID,
	SOUND_BUTTER_ID,
	SOUND_JACK_SURPRISE_ID,
	SOUND_JACK_SURPRISE2_ID,
	SOUND_NEWSPAPER_RARRGH_ID,
	SOUND_NEWSPAPER_RARRGH2_ID,
	SOUND_NEWSPAPER_RIP_ID,
	SOUND_SQUASH_HMM_ID,
	SOUND_SQUASH_HMM2_ID,
	SOUND_VASE_BREAKING_ID,
	SOUND_POOL_CLEANER_ID,
	SOUND_MAGNETSHROOM_ID,
	SOUND_LADDER_ZOMBIE_ID,
	SOUND_GARGANTUAR_THUMP_ID,
	SOUND_BASKETBALL_ID,
	SOUND_FIREPEA_ID,
	SOUND_IGNITE_ID,
	SOUND_IGNITE2_ID,
	SOUND_READYSETPLANT_ID,
	SOUND_DOOMSHROOM_ID,
	SOUND_EXPLOSION_ID,
	SOUND_FINALWAVE_ID,
	SOUND_REVERSE_EXPLOSION_ID,
	SOUND_RVTHROW_ID,
	SOUND_SHIELDHIT_ID,
	SOUND_SHIELDHIT2_ID,
	SOUND_BOSSEXPLOSION_ID,
	SOUND_CHERRYBOMB_ID,
	SOUND_BONK_ID,
	SOUND_SWING_ID,
	SOUND_RAIN_ID,
	SOUND_LIGHTFILL_ID,
	SOUND_PLASTICHIT_ID,
	SOUND_PLASTICHIT2_ID,
	SOUND_JALAPENO_ID,
	SOUND_BALLOONINFLATE_ID,
	SOUND_BIGCHOMP_ID,
	SOUND_MELONIMPACT_ID,
	SOUND_MELONIMPACT2_ID,
	SOUND_PLANTGROW_ID,
	SOUND_SHOOP_ID,
	SOUND_TAPGLASS_ID,
	SOUND_JUICY_ID,
	SOUND_COFFEE_ID,
	SOUND_WAKEUP_ID,
	SOUND_LOWGROAN_ID,
	SOUND_LOWGROAN2_ID,
	SOUND_PRIZE_ID,
	SOUND_YUCK_ID,
	SOUND_YUCK2_ID,
	SOUND_GRASSSTEP_ID,
	SOUND_SHOVEL_ID,
	SOUND_COBLAUNCH_ID,
	SOUND_WATERING_ID,
	SOUND_POLEVAULT_ID,
	SOUND_GRAVESTONE_RUMBLE_ID,
	SOUND_DIRT_RISE_ID,
	SOUND_FERTILIZER_ID,
	SOUND_PORTAL_ID,
	SOUND_BUGSPRAY_ID,
	SOUND_SCREAM_ID,
	SOUND_PAPER_ID,
	SOUND_MONEYFALLS_ID,
	SOUND_IMP_ID,
	SOUND_IMP2_ID,
	SOUND_HYDRAULIC_SHORT_ID,
	SOUND_HYDRAULIC_ID,
	SOUND_GARGANTUDEATH_ID,
	SOUND_CERAMIC_ID,
	SOUND_BOSSBOULDERATTACK_ID,
	SOUND_CHIME_ID,
	SOUND_CRAZYDAVESHORT1_ID,
	SOUND_CRAZYDAVESHORT2_ID,
	SOUND_CRAZYDAVESHORT3_ID,
	SOUND_CRAZYDAVELONG1_ID,
	SOUND_CRAZYDAVELONG2_ID,
	SOUND_CRAZYDAVELONG3_ID,
	SOUND_CRAZYDAVEEXTRALONG1_ID,
	SOUND_CRAZYDAVEEXTRALONG2_ID,
	SOUND_CRAZYDAVEEXTRALONG3_ID,
	SOUND_CRAZYDAVECRAZY_ID,
	SOUND_PHONOGRAPH_ID,
	SOUND_DANCER_ID,
	SOUND_FINALFANFARE_ID,
	SOUND_CRAZYDAVESCREAM_ID,
	SOUND_CRAZYDAVESCREAM2_ID,
	RESOURCE_ID_MAX
};

BLOOM_API Image *GetImageById(int theId);
BLOOM_API Font *GetFontById(int theId);
BLOOM_API int GetSoundById(int theId);

BLOOM_API Image *&GetImageRefById(int theId);
BLOOM_API Font *&GetFontRefById(int theId);
BLOOM_API int &GetSoundRefById(int theId);

BLOOM_API OldResourceId GetIdByImage(Image *theImage);
BLOOM_API OldResourceId GetIdByFont(Font *theFont);
BLOOM_API OldResourceId GetIdBySound(int theSound);

BLOOM_API ResourceId GetStringIdById(int theId);
//BLOOM_API OldResourceId GetIdByStringId(const char *theStringId);

} // namespace Sexy
